#include "ErrorsManager.h"

#define CREATE_ERROR(func_name, m_error, code) \
    void func_name (std::vector<Token>::iterator token) { std::cerr << m_error << token->lineNumber << "." << std::endl; exit(code); }

CREATE_ERROR(forgotValue, "Vous devez specifier une valeur, ligne ", 1)
CREATE_ERROR(forgotName, "Vous devez donner un nom, ligne ", 2)
CREATE_ERROR(forgotType, "Vous devez donner un type, ligne ", 3)
CREATE_ERROR(forgotEqualOperator, "Vous devez inserer '->' pour inclure une valeur, ligne ", 4)
CREATE_ERROR(differentTypes, "Vous avez precise un type different d'un type de valeur (exemple: pour les variables on peut pas preciser un type entier pour un nombre decimal), ligne ", 4)
CREATE_ERROR(VARIABLE_Instruction_Exist, "La variable definit a deja ete declare sous le meme nom, ligne ", 5)
CREATE_ERROR(CHANGER_Instruction_unknowVariable, "Le nom de la variable precise n'est pas declare, ligne ", 6)
CREATE_ERROR(missingparameter, "Vous devez indiquer un parametre pour preciser l'action, ligne ", 7)
CREATE_ERROR(invalidparameter, "Le parametre indiquer est invalide, ligne ", 8)
CREATE_ERROR(unknowfile, "Le fichier indiquer n'est pas reconnu, mettez bien le nom du fichier entre '\"', ligne ", 9)
CREATE_ERROR(variable_no_mutable, "La variable est constante ainsi elle ne peut changer de valeur, ligne ", 10)
CREATE_ERROR(forgotvariable, "Vous devez preciser une variable, ligne ", 11)
CREATE_ERROR(IMPORT_pathstringormissing, "Vous devez preciser le chemin vers le fichier .fpl, ligne ", 12)
CREATE_ERROR(CONVERT_IntToBool, "Pour convertir une variable de type entier vers un booleen il faut que ce soit un '1' ou '0' pour 'vrai' ou 'faux', ligne ", 13)
CREATE_ERROR(CONVERT_BoolToInt, "Pour convertir une variable de type booleen vers un entier il faut que ce soit un 'vrai' ou 'faux' pour '1' ou '0', ligne ", 14)
CREATE_ERROR(CONVERT_StringToInt, "Votre variable de type texte ne peut pas devenir un entier car elle ne contient pas un entier en valeur, ligne ", 15)
CREATE_ERROR(CONVERT_StringToDouble, "Votre variable de type texte ne peut pas devenir un nombre decimal car elle ne contient pas un nombre decimal en valeur, ligne ", 16)
CREATE_ERROR(CONVERT_impossible, "Il est impossible de convertir votre variable en un autre type, ligne ", 17)
CREATE_ERROR(forgotToOpenCode, "Vous devez ouvrir les accolades pour ouvrir un nouveau bloc de code, ligne ", 18)
CREATE_ERROR(VERIFIER_CAS_title, "Vous devez commencer avec le 'titre' 'cas' pour indiquer un nouvelle verification dans l'instruction 'verifier', ligne ", 19)
CREATE_ERROR(VERIFIER_CAS_openCode, "Vous devez ouvrir avec ':' pour ouvrir un nouveau bloc de code dans l'instruction 'verifier', ligne ", 20)
CREATE_ERROR(forgotConditionalOperator, "Vous devez ajouter un operateur conditionel ('>', '<', '=', '>=' ou '<='), ligne ", 21)
CREATE_ERROR(TANTQUE_Vir_forgot, "Vous devez rajouter ',' pour continuer l'expression de la boucle, ligne ", 22)
CREATE_ERROR(TANTQUE_wrong_action, "Vous devez preciser une action a effectuer sur votre variable precise avec 'augmenter' ou 'diminuer' puis indiquer la valeur que vous allez ajouter ou retirer, ligne ", 23)
CREATE_ERROR(TANTQUE_wrong_conditionalOperator, "L'operateur n'est pas disponible avec l'instruction 'tantque', ligne ", 24)
CREATE_ERROR(forgotOpenParenthese, "Vous devez ouvrir les parenthese, ligne ", 25)
CREATE_ERROR(FUNC_needToAddParameter, "Vous devez ajouter ',' pour continuer a donner des parametre -> '[type] [name], [type] [name], [type] [name], ...', ligne ", 26)
CREATE_ERROR(FUNC_doesNotExist, "La fonction est introuvable, il faut qu'elle soit definit avant son utilisation, ligne ", 27)
CREATE_ERROR(FUNC_needArg, "Vous devez preciser une argument de la fonction valide, ligne ", 28)
CREATE_ERROR(FUNC_wrongTypeArg, "Type non cohérent avec un argument, ligne ", 29)
CREATE_ERROR(FUNC_needToAddArgumentInCall, "Vous devez ajouter ',' pour continuer a donner des les arguments -> '[name] [value], ...', ligne ", 30)
CREATE_ERROR(TANTQUE_varWrongType, "La variable doit etre de type entier ou decimal, ligne ", 31)
CREATE_ERROR(TANTQUE_valueWrongType, "La/Les valeur(s) precise doit/doivent etre de type entier ou decimal, ligne ", 32)
CREATE_ERROR(forgotOpenBloc, "Vous devez utiliser '[' pour ouvrir un nouveau bloc et le fermer avec ']', ligne ", 33)